In [3]:
#1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
array

array([[59, 49, 17],
       [71, 40, 33],
       [15, 36, 33]])

In [4]:
array.T

array([[59, 71, 15],
       [49, 40, 36],
       [17, 33, 33]])

In [5]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np
array_1d = np.arange(10)
(array_1d)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array_2x5 = array_1d.reshape(2, 5)
array_2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
array_5x2 = array_2x5.reshape(5, 2)
array_5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [63]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np
array_4x4 = np.random.rand(4, 4)
array_4x4

array([[0.22866939, 0.57042762, 0.97405164, 0.06375973],
       [0.65992066, 0.13542688, 0.64410275, 0.48051628],
       [0.39066967, 0.74696382, 0.44665862, 0.23039431],
       [0.31938534, 0.77280463, 0.08476092, 0.17925016]])

In [68]:
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:\n", array_6x6)


6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.22866939 0.57042762 0.97405164 0.06375973 0.        ]
 [0.         0.65992066 0.13542688 0.64410275 0.48051628 0.        ]
 [0.         0.39066967 0.74696382 0.44665862 0.23039431 0.        ]
 [0.         0.31938534 0.77280463 0.08476092 0.17925016 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [23]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np
array = np.arange(10, 65, 5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [38]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
array = np.array(['python', 'numpy', 'pandas'])
array

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [39]:
uppercase_array = np.char.upper(array)      # Convert to uppercase
uppercase_array

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [40]:
lowercase_array = np.char.lower(array)      # Convert to lowercase
lowercase_array

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [41]:
titlecase_array = np.char.title(array)      # Convert to title case
titlecase_array

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [42]:
capitalize_array = np.char.capitalize(array) # Capitalize the first letter of each element
capitalize_array

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [36]:
#6.Generate a NumPy array of words. Insert a space between each character of every word in the array
words_array = np.array(['python', 'numpy', 'pandas'])
spaced = np.char.join(' ', words_array)
spaced

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [49]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [51]:
addition = array1 + array2
addition

array([[ 8, 10, 12],
       [14, 16, 18]])

In [52]:
subtraction = array1 - array2
subtraction

array([[-6, -6, -6],
       [-6, -6, -6]])

In [53]:
multiplication = array1 * array2
multiplication

array([[ 7, 16, 27],
       [40, 55, 72]])

In [54]:
division = array1 / array2
division

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [57]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
diagonal_elements = np.diag(identity_matrix)
diagonal_elements

array([1., 1., 1., 1., 1.])

In [70]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

random_array = np.random.randint(0, 1001, size=100)
random_array
prime_numbers = np.array([num for num in random_array if is_prime(num)])
prime_numbers

array([863, 547, 941, 233, 523, 809, 541, 997, 761, 257, 101,  71, 421,
       257, 349, 281, 409, 223])

In [72]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
daily_temperatures = np.random.uniform(20, 35, 30)
daily_temperatures

array([30.7095047 , 25.47733608, 20.52620485, 27.65259091, 33.24574495,
       24.68355394, 32.14753232, 20.60683573, 25.53795028, 34.70506819,
       21.66083899, 23.98769653, 31.27119446, 33.6199068 , 28.44977594,
       28.90581512, 34.58173314, 32.30322355, 32.15331169, 21.01068934,
       28.75071381, 26.87555957, 31.96079338, 30.0533574 , 21.36211231,
       26.42980546, 23.99997648, 33.75406893, 28.12852742, 33.57707165])

In [73]:
reshaped_temperatures = np.array_split(daily_temperatures, 5)
reshaped_temperatures

[array([30.7095047 , 25.47733608, 20.52620485, 27.65259091, 33.24574495,
        24.68355394]),
 array([32.14753232, 20.60683573, 25.53795028, 34.70506819, 21.66083899,
        23.98769653]),
 array([31.27119446, 33.6199068 , 28.44977594, 28.90581512, 34.58173314,
        32.30322355]),
 array([32.15331169, 21.01068934, 28.75071381, 26.87555957, 31.96079338,
        30.0533574 ]),
 array([21.36211231, 26.42980546, 23.99997648, 33.75406893, 28.12852742,
        33.57707165])]

In [75]:
weekly_averages = np.array([week.mean() for week in reshaped_temperatures])
weekly_averages

array([27.0491559 , 26.44098701, 31.5219415 , 28.4674042 , 27.87526038])

In [76]:
for i, avg in enumerate(weekly_averages, start=1):
    print(f"Week {i} average temperature: {avg:.2f}°C")

Week 1 average temperature: 27.05°C
Week 2 average temperature: 26.44°C
Week 3 average temperature: 31.52°C
Week 4 average temperature: 28.47°C
Week 5 average temperature: 27.88°C
